---
apiVersion: v1
kind: Namespace
metadata:
  name: block-spammer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-block-spammer
  namespace: block-spammer
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: block-spammer
    app.kubernetes.io/component: block-spammer
    app.kubernetes.io/instance: block-spammer
  name: block-spammer
  namespace: block-spammer
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: block-spammer
  template:
    metadata:
      labels:
        deployment: block-spammer
    spec:
      containers:
      - image: quay.io/mavazque/storage-spammer:block
        imagePullPolicy: IfNotPresent
        name: block-spammer
        args:
        - "--files"
        - "10"
        - "--wait-time"
        - "10"
        - "--file-size"
        - "100"
        - "--file-path"
        - "/data/"
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: spammer-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: spammer-vol
        persistentVolumeClaim:
          claimName: pvc-block-spammer
