---
apiVersion: v1
kind: Namespace
metadata:
  name: s3-spammer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-spammer
  namespace: s3-spammer
  labels:
    app: s3-spammer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-spammer
  template:
    metadata:
      labels:
        app: s3-spammer
    spec:
      serviceAccountName: default
      containers:
      - name: s3-spammer
        imagePullPolicy: IfNotPresent
        image: quay.io/mavazque/storage-spammer:s3
        args:
        - "--files"
        - "10"
        - "--wait-time"
        - "10"
        - "--file-size"
        - "100"
        - "--bucket-name"
        - "s3-spammer-bucket"
        env:
          - name: S3_ENDPOINT
            value: "https://s3.openshift-storage.svc"
          - name: S3_NO_VERIFY_SSL
            value: "True"
          - name: S3_ACCESS_KEY
            value: "changeme"
          - name: S3_SECRET_KEY
            value: "changeme"
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  name: s3-spammer-bucket
  namespace: s3-spammer
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: s3-spammer-bucket
  objectBucketName: obc-openshift-storage-s3-spammer-bucket
  storageClassName: openshift-storage.noobaa.io
